version: '2.1'

services:
  job-scheduler-api:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: docker.artifactory.reform.hmcts.net/reform/job-scheduler-api
    container_name: job-scheduler-api
    environment:
      - S2S_URL
      - S2S_SECRET
      - JOB_SCHEDULER_DB_USERNAME=jobscheduler
      - JOB_SCHEDULER_DB_PASSWORD
      - JOB_SCHEDULER_DB_HOST=job-scheduler-database
      - JOB_SCHEDULER_DB_PORT=5432
      # these environment variables are used by java-logging library
      - ROOT_APPENDER
      - JSON_CONSOLE_PRETTY_PRINT
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_NAME
      - REFORM_TEAM
      - REFORM_ENVIRONMENT
    ports:
      - $SERVER_PORT:$SERVER_PORT
    depends_on:
      job-scheduler-database:
        condition: service_healthy
  job-scheduler-database:
    build:
      context: docker/database
    image: docker.artifactory.reform.hmcts.net/reform/job-scheduler-database
    container_name: job-scheduler-database
    environment:
      - JOB_SCHEDULER_DB_PASSWORD
    ports:
      - 5428:5432
    volumes:
      - job-scheduler-database-data:/var/lib/postgresql/data

volumes:
  job-scheduler-database-data:
